### ISSUE TITLE
Update GitVersion Usage In Build & .NET 8

### ISSUE THREAD

**Issue by mitchelsellers** [IowaComputerGurus/github-cost-visualizer#42]
The usage of GitTools needs to be updated to utilize the new versions, this involves multiple changes.

## 'GitVersion.yml` Changes

* Change `tag` to `label`
* Change `tag-number-pattern` to `label-number-pattern`
* Add to the `develop` branch rules the following after the `increment: Patch` line

```` yml
    prevent-increment:
      when-current-commit-tagged: true
````

## Build File Changes

Update the Install GitVersion and Determine Version ones to be the following. 

```` yml
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        useConfigFile: true
````

> [!NOTE]  
> This is a change from the prior usage of `dotnet tool` to do the install, and this should be done for ALL instances of usage of GitVersion

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1463912425) by [Unito](https://www.unito.io)
